# This is a basic workflow to help you get started with Actions

name: Development CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ''

      - name: Current Branch
        run: echo ${GITHUB_REF##*/}
        
      - name: npm install
        run: npm install

      - name: npm run webpack
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: S3 Deploy
        run: aws s3 sync ./dist s3://superant-dev
      
      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id EI8GLQNZYI2N5 --paths / /index.html
